#!/usr/bin/env bash

set -eu

# This hook will make sure that people are writing commit messages that comply with our standards
# http://chris.beams.io/posts/git-commit/

# Rule 3 start with capital letter

if ! grep --quiet '^[A-Z]' $1
then
    echo "Commit messages must start with a capital letter!"
    exit 1
fi

# Rule 4 do not end subject line with a period (or period with whitespace after)

if head -1 "$1" | grep --quiet '\.\s*$'
then
    echo "Subject line should not end in a period!"
    exit 1
fi