#!/usr/bin/env bash

set -eu

# This hook will make sure that people are writing commit messages that comply with our standards
# http://chris.beams.io/posts/git-commit/

commit_message_file="$1"

# Rule 3 start with capital letter

if ! grep --quiet '^[A-Z]' $commit_message_file
then
    echo "Commit messages must start with a capital letter!"
    exit 1
fi

# Rule 4 do not end subject line with a period (or period with whitespace after)

if head -1 "$commit_message_file" | grep --quiet '\.\s*$'
then
    echo "Subject line should not end in a period!"
    exit 1
fi

# Rule 2 limit subject line to 50 characters - except for the automated merge commit messages which can be longer

subject_line=$(head -1 "$commit_message_file")

if ! grep --quiet '^Merge ' $commit_message_file && [ "${#subject_line}" -gt 50 ]
then
    echo "Subject line should not exceed 50 characters. You entered ${#subject_line}."
    exit 1
fi

# Rule 1 body (if present) must be separated from subject line by a blank line

# Rule 6 body (if present) must be wrapped at 72 characters
